version: '3'

services:
  doc-staging:
    container_name: doc-staging
    build:
      context: ./
      dockerfile: ./docker/alpine/Dockerfile
    environment:
      - BASE_PATH=/
    ports:
      - "81:80"