---
# tasks file for roles/webservers
- name: Login to gitlab
  community.docker.docker_login:
    registry_url: "{{ regestry_login }}"
    username: "{{ regestry_user }}"
    password: "{{ regestry_password }}"
    reauthorize: true

- name: Create docker container for "{{ environment_name }}"
  community.docker.docker_container:
    name: "web-{{ environment_name }}"
    state: started
    recreate: true
    restart: true
    pull: true
    image: "{{ regestry_image }}:{{ environment_name }}"
    env:
      SUB_DIR: "/{{ environment_name }}/"
      BACKEND_BASE_URL: "https://poppen.antwaan.be/{{ environment_name }}-api"
    volumes:
      - "/opt/docker/logs/web-{{ environment_name }}:/var/log"
    networks:
      - name: "bridge-{{ environment_name }}"
