version: '3'
services:
  #reactjs:
  #  image: https://registry.gitlab.com/ikdoeict/vakken/opo_agile_team_project/projecten/2324_atp_poppen/web:latest
  #  ports:
  #    - "8080:80"

  web:
    build:
      context: ./
      dockerfile: ./docker/alpine/Dockerfile
    container_name: web
    environment:
      - BACKEND_BASE_URL=http://localhost:8080
      - SUB_DIR=/
    ports:
      - 80:80